spring.application.name=zero-trust
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_rRtIu4AqR
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_rRtIu4AqR/.well-known/jwks.json