spring.application.name=zero-trust
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_rRtIu4AqR
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_rRtIu4AqR/.well-known/jwks.json
aws.healthlake.endpoint=https://healthlake.ap-southeast-2.amazonaws.com/datastore/1a7f1259382e5d3b195f40b3c44c78c0/r4/
aws.region=ap-southeast-2